import { Transaction, TransactionStatus, TransactionType, Currency, PaymentMethod, User, Role, Project, Budget } from './types';

export const MOCK_USERS: User[] = [
  { id: 'johan', name: 'Johan', role: Role.Accountant, email: 'johan@uneural.org' },
  { id: 'lead_ops', name: 'Lead Operaciones', role: Role.Lead, email: 'lead.ops@uneural.org' },
  { id: 'admin_user', name: 'Admin', role: Role.Admin, email: 'admin@uneural.org' },
];

export const MOCK_PROJECTS: Project[] = [
  { id: 'hackaton-sept', name: 'Hackatón Septiembre', lead: 'lead_ops' },
  { id: 'smart-cities-3d', name: 'Smart Cities 3D Modeling', lead: 'lead_ops' },
  { id: 'educational-series', name: 'Serie Educativa IEEE', lead: 'johan' },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn_1',
    orgId: 'uneural',
    groupId: 'operaciones',
    projectId: 'hackaton-sept',
    type: TransactionType.Expense,
    category: 'logistica/alimentos',
    vendor: 'Panadería El Punto',
    date: '2025-09-08',
    amount: 85000,
    currency: Currency.COP,
    tax: 0,
    method: PaymentMethod.Cash,
    description: 'Desayunos hackatón',
    attachments: ['file_abc123'],
    createdBy: 'johan',
    source: 'ocr+audio',
    confidence: 0.91,
    status: TransactionStatus.Posted,
    approvals: [{ by: 'lead_ops', at: '2025-09-08T15:21:00Z' }],
    invoiceNumber: 'F-00123',
    attendeeCount: 25,
    department: 'Ops'
  },
  {
    id: 'txn_2',
    orgId: 'uneural',
    groupId: 'tech',
    projectId: 'smart-cities-3d',
    type: TransactionType.Expense,
    category: 'membresías/servicios',
    vendor: 'Cloud Services Inc.',
    date: '2025-09-10',
    amount: 50,
    currency: Currency.USD,
    tax: 0,
    method: PaymentMethod.CreditCard,
    description: 'Suscripción mensual a servidor GPU',
    attachments: ['file_def456'],
    createdBy: 'johan',
    source: 'pdf',
    confidence: 0.99,
    status: TransactionStatus.Posted,
    approvals: [],
    recurring: true,
    department: 'Programs'
  },
  {
    id: 'txn_3',
    orgId: 'uneural',
    groupId: 'eventos',
    projectId: 'educational-series',
    type: TransactionType.Income,
    category: 'patrocinios',
    vendor: 'IEEE Computer Society',
    date: '2025-09-05',
    amount: 500000,
    currency: Currency.COP,
    tax: 0,
    method: PaymentMethod.Transfer,
    description: 'Patrocinio para serie de talleres',
    attachments: ['file_ghi789'],
    createdBy: 'admin_user',
    source: 'email',
    confidence: 1.0,
    status: TransactionStatus.Posted,
    approvals: [],
    fundingSource: 'IEEE_SAC',
    department: 'Partnerships'
  },
   {
    id: 'txn_4',
    orgId: 'uneural',
    groupId: 'operaciones',
    type: TransactionType.Expense,
    category: 'marketing/diseño',
    vendor: 'Imprenta Veloz',
    date: '2025-09-12',
    amount: 450000,
    currency: Currency.COP,
    tax: 0,
    method: PaymentMethod.Transfer,
    description: 'Impresión de pendones para Hackaton',
    attachments: ['file_jkl012'],
    createdBy: 'johan',
    source: 'image',
    confidence: 0.82,
    status: TransactionStatus.Pending,
    approvals: [],
    department: 'Comms',
    policyViolations: ['Requiere aprobación: monto superior a 300.000 COP.'],
  },
];

export const MOCK_BUDGETS: Budget[] = [
    { id: 'bud_1', orgId: 'uneural', projectId: 'hackaton-sept', period: '2025-09', cap_amount: 1500000, spent_amount: 640000 },
    { id: 'bud_2', orgId: 'uneural', projectId: 'smart-cities-3d', period: '2025-09', cap_amount: 2000000, spent_amount: 190000 },
    { id: 'bud_3', orgId: 'uneural', groupId: 'operaciones', period: '2025-09', cap_amount: 500000, spent_amount: 120000 },
];